# Site settings
title: Chestnut的博客
email: mini.chenli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    new blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chestnutchen.tk" # the base hostname & protocol for your site
twitter_username: chectnut_chen
github_username:  chestnutchen

# Build settings
markdown: kramdown

# Pages
include: ['slides']
