# Site settings
title: Chestnut的博客
email: mini.chenli@gmail.com
description: "chestnut吐槽的地方"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chestnutchen.tk" # the base hostname & protocol for your site
twitter_username: chectnut_chen
github_username:  chestnutchen

# Build settings
markdown: redcarpet
# markdown: kramdown

# Pages
include: ['slides']

